import org.apache.hadoop.security.protocolPB.RefreshAuthorizationPolicyProtocolServerSideTranslatorPB;
public class FunctionUse19058 {
public void funcUse() {
RefreshAuthorizationPolicyProtocolServerSideTranslatorPB refreshauthorizationpolicyprotocolserversidetranslatorpb = new RefreshAuthorizationPolicyProtocolServerSideTranslatorPB();
}
}